version: "3.9"

services:
  # db:
  #   init: true
  #   container_name: db
  #   image: postgres:latest
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   networks:
  #     - transnet
  #   ports:
  #     - "5432:5432"

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - "3215:8080"
  #   networks:
  #     - transnet

  back:
    init: true
    container_name: back
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    build:
      context: ./project/back
    networks:
      - transnet
    restart: unless-stopped

  front:
    init: true
    container_name: front
    depends_on:
      - back
    build:
      context: ./project/front
    networks:
      - transnet
    restart: unless-stopped
    ports:
      - "8080:8080"

  mongodb:
    init: true
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: database
    networks:
      - transnet

  php:
    depends_on:
      - front
    container_name: php
    build:
      context: ./project/wik
    networks:
      - transnet
    restart: unless-stopped
    ports:
      - "8081:80"
      
volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      device: ./project/mongodb/data
      o: bind

networks:
  transnet:
    driver: bridge
